### PR TITLE
fix: fix key error in sequences list

### LINKED ISSUE #25: ShotsView error with key
There's an error with the key prop on the `ShotsView` component:

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `ShotsView`. See https://reactjs.org/link/warning-keys for more information.
```

Check the documentation: https://reactjs.org/docs/lists-and-keys.html

### PR DESCRIPTION
**Pull request by GuillaumeRoeder**
sould close #25

### CODE REVIEW

File: src/components/pages/ExplorerPage/views/ShotsView.tsx [hunk 1]
```diff
@@ -40,15 +42,20 @@ const ShotsView: React.FC<{ listView: boolean }> = ({ listView }) => {
...
-          <div key={seq.id}>
-            <h2 style={{ marginBottom: 0, marginTop: 0 }}>
-              {seq.name} {seq.nb_frames && <h4>({seq.nb_frames} frames)</h4>}
-            </h2>
-            <EntitiesView entities={seq.shots} listView={listView} />
-            {i !== data.project.sequences.length - 1 && <br />}
-          </div>
-        ))}
+        data.project.sequences.map((seq, i) => {
+          console.log(seq);
```
Comment (johhnry) [inline src/components/pages/ExplorerPage/views/ShotsView.tsx:46]: Remove this console.log

**Review by johhnry — APPROVED** [review]
LGTM, thanks!
