### PR TITLE
fix: handle missing project error

### LINKED ISSUE #26: Error data[0] (NO initial project) when login

### PR DESCRIPTION
**Pull request by GuillaumeRoeder**
Should close #26

### CODE REVIEW

File: src/context/AuthContext.tsx [hunk 1]
```diff
@@ -1,3 +1,4 @@
+import { Password } from "@mui/icons-material";
```
Comment (johhnry) [inline src/context/AuthContext.tsx:1]: Should remove this import since it's not needed

File: src/components/pages/HomePage/HomePage.tsx [hunk 2]
```diff
@@ -6,6 +6,14 @@ import PageWrapper from "../PageWrapper/PageWrapper";
 const HomePage: React.FC = () => {
   const auth = useAuth();
 
+  if (auth.currentProjectId === undefined) {
+    return (
+      <PageWrapper title={`Welcome ${auth.user?.full_name}`}>
```
Comment (johhnry) [inline src/components/pages/HomePage/HomePage.tsx:11]: The `PageWrapper` component should wrap the whole return. It's repeated twice here ;)

File: src/components/Menu/Menu.tsx [hunk 3]
```diff
@@ -47,27 +49,36 @@ const Menu: React.FC<MenuProps> = ({ closeMenu, open }) => {
...
-                    ? "primary"
-                    : "text.disabled"
-                }
-                onClick={closeMenu}
-              >
-                {link.text}
-              </Link>
-            </Grid>
-          ))}
+          {links.map((link, i) => {
```
Comment (johhnry) [inline src/components/Menu/Menu.tsx:52]: We can do two things to improve the readability here:

```jsx
links.map((link, i) => {
  (condition) ? <Link> ... </Link> : null
}
```

where `condition` is 

```javascript
!(!auth.currentProjectId && link.needProjectId)
```

_(note the negation since we want to render the link if it's we don't need the project Id)_

or

use `filter` to filter out the links in the array before mapping them:

```jsx
links.filter(link => !(!auth.currentProjectId && link.needProjectId))
     .map((link, i) => <Link> ... </Link>)
```

File: src/components/pages/HomePage/HomePage.tsx [hunk 4]
```diff
@@ -5,20 +5,15 @@ import PageWrapper from "../PageWrapper/PageWrapper";
 
 const HomePage: React.FC = () => {
   const auth = useAuth();
+  let message = "This app is under construction...";
```
Comment (johhnry) [inline src/components/pages/HomePage/HomePage.tsx:8]: Use `const` instead of `let` since the value is not going to change. See: https://medium.com/dailyjs/use-const-and-make-your-javascript-code-better-aac4f3786ca1

**Review by johhnry — APPROVED** [review]
LGTM

**Review by Acedyn — APPROVED** [review]
